import { useEffect, useState } from "react";
import "./App.css";
const API = import.meta.env.VITE_API_URL || "http://localhost:5001/api";
const menu = [["counter","Bán vé tại quầy","▣"],["rooms","Quản lý phòng và ghế","▤"],["shift","Báo cáo ca làm việc","▥"],["history","Lịch sử giao dịch","◷"]];
const titles = { counter:["Bán vé tại quầy","Bán vé trực tiếp","Chọn suất chiếu, ghế còn trống và hoàn tất thanh toán tiền mặt."], rooms:["Quản lý phòng và ghế","Sơ đồ phòng chiếu","Kiểm tra tình trạng phòng và cập nhật trạng thái ghế."], shift:["Báo cáo ca làm việc","Tổng kết ca làm việc","Xem doanh thu, số vé bán và các giao dịch trong ca của bạn."], history:["Lịch sử giao dịch","Các giao dịch gần đây","Tra cứu hóa đơn, trạng thái thanh toán và lịch sử bán vé."] };
const money = new Intl.NumberFormat("vi-VN", { style:"currency", currency:"VND", maximumFractionDigits:0 });
const headers = () => { const token = localStorage.getItem("staffAccessToken") || localStorage.getItem("adminAccessToken") || localStorage.getItem("accessToken"); return token ? { Authorization:`Bearer ${token}` } : {}; };
const consumeStaffTokenFromHash = () => { const hash = new URLSearchParams(window.location.hash.slice(1)); const token = hash.get("staffToken"); if (!token) return; localStorage.setItem("staffAccessToken", token); window.history.replaceState(null, "", `${window.location.pathname}${window.location.search}`); };
async function api(path, options={}) { const response = await fetch(`${API}${path}`, { ...options, headers:{ "Content-Type":"application/json", ...headers(), ...options.headers } }); const body = await response.json().catch(()=>({})); if (!response.ok || !body.success) throw new Error(body.message || "Không thể kết nối máy chủ."); return body.data; }

export default function App() {
  const [active,setActive] = useState("counter"), [collapsed,setCollapsed] = useState(false), [mobile,setMobile] = useState(false); const [crumb,title,description] = titles[active];
  consumeStaffTokenFromHash();
  return <div className={`staff-layout ${collapsed ? "sidebar-collapsed" : ""}`}><aside className={`sidebar ${collapsed ? "collapsed" : ""} ${mobile ? "mobile-open" : ""}`}><div className="sidebar-logo"><div className="sidebar-logo-icon">A</div><span className="sidebar-logo-text">AuraCinema</span></div><nav className="sidebar-nav"><div className="sidebar-section-title">Nhân viên</div>{menu.map(([id,label,icon])=><button key={id} className={`sidebar-link ${active===id?"active":""}`} onClick={()=>{setActive(id);setMobile(false)}} title={collapsed?label:undefined}><span className="sidebar-link-icon">{icon}</span><span className="sidebar-link-text">{label}</span></button>)}</nav><div className="sidebar-footer"><div className="sidebar-footer-avatar">N</div><div className="sidebar-footer-details"><strong>Nhân viên</strong><span>Nhân viên quầy vé</span></div></div></aside>{mobile&&<button className="sidebar-overlay" onClick={()=>setMobile(false)} aria-label="Đóng menu"/>}<div className="staff-main"><header className="header"><div className="header-left"><button className="header-toggle desktop-toggle" onClick={()=>setCollapsed(!collapsed)}>☰</button><button className="header-toggle mobile-toggle" onClick={()=>setMobile(true)}>☰</button><div className="breadcrumb"><span>Nhân viên</span><b>/</b><strong>{crumb}</strong></div></div><div className="header-right"><label className="header-search"><span>⌕</span><input placeholder="Tìm kiếm..."/></label><button className="header-icon">♢<i/></button><div className="header-user"><div>N</div><span><strong>Nhân viên</strong><small>Quầy vé</small></span></div></div></header><main className="staff-content"><section className="page-heading"><span>{crumb}</span><h1>{title}</h1><p>{description}</p></section>{active==="counter"?<CounterSale/>:<section className="content-card empty-page"><h2>{crumb}</h2><p>Chức năng này đang được chuẩn bị cho nhân viên rạp.</p></section>}</main></div></div>;
}

function CounterSale() {
  const [showtimes,setShowtimes] = useState([]), [current,setCurrent] = useState(null), [seats,setSeats] = useState([]), [selected,setSelected] = useState([]), [loading,setLoading] = useState(true), [seatLoading,setSeatLoading] = useState(false), [busy,setBusy] = useState(false), [error,setError] = useState(""), [sale,setSale] = useState(null);
  const chosen = seats.filter(s=>selected.includes(s.id)); const total = chosen.reduce((sum,s)=>sum+s.price,0);
  useEffect(()=>{ let live=true; api("/staff/pos/showtimes").then(d=>live&&setShowtimes(d)).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false)); return()=>{live=false}; },[]);
  const choose = async (showtime) => { setCurrent(showtime);setSelected([]);setSeats([]);setSale(null);setError("");setSeatLoading(true); try { const data=await api(`/showtime-seats?showtime_id=${showtime.id}`); setSeats(data.map(normalizeSeat)); } catch(e){setError(e.message)} finally {setSeatLoading(false)} };
  const toggle = seat => seat.status==="available"&&setSelected(list=>list.includes(seat.id)?list.filter(id=>id!==seat.id):[...list,seat.id]);
  const pay = async () => { if (!current||!selected.length) return; setBusy(true);setError("");try { const data=await api("/staff/pos/sales",{method:"POST",body:JSON.stringify({showtime_id:current.id,showtime_seat_ids:selected,payment_method:"cash"})});setSale(data);setSeats(list=>list.map(s=>selected.includes(s.id)?{...s,status:"booked"}:s));setSelected([]); } catch(e){setError(e.message);choose(current)} finally {setBusy(false)} };
  const print = async () => { try { await api(`/staff/pos/sales/${sale.booking_id}/print`,{method:"POST"});window.print(); } catch(e){setError(e.message)} };
  return <div className="pos-layout"><section className="pos-workspace"><Step number="1" title="Chọn phim và suất chiếu" text={loading?"Đang tải suất chiếu...":`${showtimes.length} suất chiếu khả dụng`}/>{!loading&&<div className="showtime-picker">{showtimes.length?showtimes.map(s=><button className={`showtime-card ${current?.id===s.id?"selected":""}`} onClick={()=>choose(s)} key={s.id}><span className="poster poster-one">{s.movie.title.slice(0,2).toUpperCase()}</span><span><strong>{s.movie.title}</strong><small>{dateTime(s.start_time)}</small><small>{s.room.cinema} · {s.room.name}</small></span><em>{s.available_seats} ghế trống</em></button>):<p className="empty-note">Không có suất chiếu khả dụng.</p>}</div>}{current&&<><Step number="2" title="Chọn ghế" text="Chỉ ghế màu tím còn trống mới có thể bán."/>{seatLoading?<p className="empty-note">Đang tải sơ đồ ghế...</p>:<SeatMap seats={seats} selected={selected} toggle={toggle}/>}</>}</section><aside className="order-panel"><h2>Thông tin đơn hàng</h2>{current?<><div className="order-row"><span>Phim</span><strong>{current.movie.title}</strong></div><div className="order-row"><span>Suất chiếu</span><strong>{dateTime(current.start_time)}</strong></div><div className="order-row"><span>Phòng</span><strong>{current.room.name}</strong></div><div className="order-seats"><span>Ghế đã chọn</span><div>{chosen.length?chosen.map(s=><b key={s.id}>{s.label}</b>):"Chưa chọn ghế"}</div></div><div className="order-total"><span>Tổng thanh toán</span><strong>{money.format(total)}</strong></div><div className="payment-method">✓ Thanh toán tiền mặt</div><button className="pay-button" disabled={!selected.length||busy} onClick={pay}>{busy?"Đang xử lý...":`Xác nhận thanh toán ${money.format(total)}`}</button></>:<p className="empty-note">Hãy chọn một suất chiếu để bắt đầu.</p>}{sale&&<div className="sale-success"><strong>Thanh toán thành công</strong><span>Mã đơn: {sale.booking_code}</span><span>Vé: {sale.tickets.map(t=>t.seat).join(", ")}</span><button onClick={print}>In vé cứng</button></div>}</aside>{error&&<div className="pos-alert">{error}</div>}</div>;
}
function Step({number,title,text}){return <div className="pos-step"><span>{number}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
function dateTime(value){return new Date(value).toLocaleString("vi-VN",{hour:"2-digit",minute:"2-digit",day:"2-digit",month:"2-digit"})}
function normalizeSeat(item){const s=item.seat_id||item.seat||{}, label=String(s.seat_code||`${s.seat_row||""}${s.seat_number||""}`).toUpperCase();return{id:item._id||item.id,label,row:s.seat_row||label.charAt(0)||"?",number:Number(s.seat_number||label.slice(1)||0),price:Number(item.price||0),status:item.status}}
function SeatMap({seats,selected,toggle}){const rows=[...new Set(seats.map(s=>s.row))].sort();return <div className="seat-map"><div className="screen">MÀN HÌNH</div><div className="seat-legend"><span><i className="available"/>Trống</span><span><i className="selected"/>Đang chọn</span><span><i className="taken"/>Đã bán / đang giữ</span></div>{rows.map(row=><div className="seat-row" key={row}><b>{row}</b><div>{seats.filter(s=>s.row===row).sort((a,b)=>a.number-b.number).map(s=><button key={s.id} disabled={s.status!=="available"} onClick={()=>toggle(s)} className={`seat ${s.status} ${selected.includes(s.id)?"selected":""}`} title={`${s.label} · ${money.format(s.price)}`}>{s.number||s.label}</button>)}</div><b>{row}</b></div>)}</div>}
